# Generated by Django 4.2.6 on 2024-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={},
        ),
        migrations.AlterModelManagers(
            name='estabelecimento',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='estabelecimento',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
