# Generated by Django 5.0.1 on 2024-02-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='descricao',
            field=models.CharField(default='', max_length=400, verbose_name='Descrição'),
        ),
    ]
