# Generated by Django 4.2.6 on 2024-02-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_cep_alter_userprofile_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
    ]
