# Generated by Django 4.2.6 on 2024-02-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='estado',
        ),
    ]
