# Generated by Django 5.0.1 on 2024-02-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_cidade_remove_userprofile_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
