# Generated by Django 5.0.1 on 2024-02-14 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosEstab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='foto_estab')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='foto_estab')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='foto_estab')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='foto_estab')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='foto_estab')),
                ('foto6', models.ImageField(blank=True, null=True, upload_to='foto_estab')),
                ('has_fotos', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
