# Generated by Django 5.0.1 on 2024-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_fotosestab'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='capacidade_pessoas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_horario',
            field=models.CharField(choices=[('hora', 'Por Hora'), ('noite', 'Por Noite')], default='hora', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='valor_aluguel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
