# Generated by Django 4.2.6 on 2024-02-23 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='membros',
            field=models.ManyToManyField(through='cliente_app.StatusPagamentoMembro', to=settings.AUTH_USER_MODEL),
        ),
    ]
