# Generated by Django 5.0.1 on 2024-02-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='grupo',
            name='ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='grupo',
            name='dia',
            field=models.IntegerField(default=29),
        ),
        migrations.AddField(
            model_name='grupo',
            name='mes',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='duracao',
            field=models.IntegerField(default=0),
        ),
    ]
