# Generated by Django 5.0.1 on 2024-02-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0002_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='membrogrupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='membrogrupo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='MembroGrupo',
        ),
    ]
