# Generated by Django 5.0.1 on 2024-02-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estab_app', '0002_datadisponibilidade_delete_disponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaMarcado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataDisponibilidade',
        ),
    ]
